### ISSUE TITLE
Publish updated NPM version

### ISSUE THREAD

**Issue by jlarmstrongiv** [cryptella-com/eml-rfc822#1]
I’ve been looking for a streaming eml parser, and your library seems great 🎉 would you publish an update to npm with the latest version from GitHub?

**Comment by ovx** [comment]
Hi, I have a new version with some fixes coming up, as well as a proper npm package. Will try to publish in the following days.

**Comment by ovx** [comment]
Version 0.0.2 published, it fixes some problems with nested multiparts and exports a convenience function parseMultipart. See tests for more examples how to use it with streams.

**Comment by jlarmstrongiv** [comment]
Thank you @ovx I look forward to giving it a try 😄 I’ll be sure to check out the tests for examples
